site_name: ANN & DL - Iara
site_author: iaravsp
site_url: https://iaravsp.github.io/ann-dl-iaravsp/
repo_url: https://github.com/iaravsp/ann-dl-iaravsp
repo_name: iaravsp/ann-dl-iaravsp

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.expand
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - markdown_grid_tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - tables

plugins:
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - search
  - minify:
      minify_html: true

extra_javascript:

  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Exercises:
    - Data: exercises/data/index.md
    - Perceptron: exercises/perceptron/index.md
    - MLP: exercises/mlp/index.md
    - VAE: exercises/vae/index.md
  - Projects: projects/index.md
